### ISSUE TITLE
v1.2.6: Muted/Highlight/Dark - color settings do not seem to work (Craft 3.8.15)

### ISSUE THREAD

**Issue by amkdev** [HOMMinteractive/hommsocialfeed#5]
After installation, the default colors are displayed. After setting up the Social Feed API path / saving the settings, the colors are gone.

<img width="1114" alt="grafik" src="https://github.com/HOMMinteractive/hommsocialfeed/assets/5300389/1914c6c7-e6df-43a0-8d41-54880a2ff85f">

**Comment by ammannbe** [comment]
Thanks for the info. This will be updated in the next release.

But setting the colors should work anyways (it's just not displayed correctly)
